export const ParentsActivityHeader = [
  {
    id: 0,
    header: [
      {
        id: "first_name",
        numeric: false,
        disablePadding: true,
        label: "First Name",
        sort: true,
        width: 180,
      },
      {
        id: "last_name",
        numeric: false,
        disablePadding: true,
        label: "Last Name",
        sort: true,
        width: 120,
      },
      {
        id: "country_code_wa",
        numeric: false,
        disablePadding: true,
        label: "Country Code Whatsapp",
        sort: true,
        width: 120,
      },
      {
        id: "whatsapp_number",
        numeric: false,
        disablePadding: true,
        label: "WhatsApp Number",
        sort: true,
        width: 120,
      },
      {
        id: "country_code_mob",
        numeric: false,
        disablePadding: true,
        label: "Country Code Mobile",
        sort: true,
        width: 120,
      },
      {
        id: "mobile",
        numeric: false,
        disablePadding: true,
        label: "Mobile",
        sort: true,
        width: 120,
      },
      {
        id: "totalChildren",
        numeric: false,
        disablePadding: true,
        label: "Total children",
        sort: true,
        width: 120,
      },
      {
        id: "addresss",
        numeric: false,
        disablePadding: true,
        label: "Address",
        sort: true,
        width: 120,
      },
      {
        id: "lat",
        numeric: false,
        disablePadding: true,
        label: "Lat",
        sort: true,
        width: 120,
      },
      {
        id: "long",
        numeric: false,
        disablePadding: true,
        label: "Long",
        sort: true,
        width: 120,
      },
      {
        id: "assigned_district",
        numeric: false,
        disablePadding: true,
        label: "Assigned Districts",
        sort: true,
        width: 120,
      },
      {
        id: "assigned_blockzone",
        numeric: false,
        disablePadding: true,
        label: "Assigned Block/Zone",
        sort: true,
        width: 120,
      },
      {
        id: "assigned_panchayat",
        numeric: false,
        disablePadding: true,
        label: "Assigned Panchayat/Ward",
        sort: true,
        width: 120,
      },
      {
        id: "assigned_village",
        numeric: false,
        disablePadding: true,
        label: "Assigned Village/Area",
        sort: true,
        width: 120,
      },
      {
        id: "batch",
        numeric: false,
        disablePadding: true,
        label: "Batch",
        sort: true,
        width: 120,
      },
    ]
  },
  {
    id: 1,
    header: [
      {
        id: "parent_whatsapp_number",
        numeric: false,
        disablePadding: true,
        label: "Parents WhatsApp Number",
        sort: true,
        width: 180,
      },
      {
        id: "childName",
        numeric: false,
        disablePadding: true,
        label: "Child Name",
        sort: true,
        width: 120,
      },
      {
        id: "dob",
        numeric: false,
        disablePadding: true,
        label: "DOB",
        sort: true,
        width: 120,
      },
      {
        id: "gender",
        numeric: false,
        disablePadding: true,
        label: "Gender",
        sort: true,
        width: 120,
      },
      {
        id: "relationship",
        numeric: false,
        disablePadding: true,
        label: "Relationship",
        sort: true,
        width: 120,
      },
      {
        id: "schoolType",
        numeric: false,
        disablePadding: true,
        label: "School Type",
        sort: true,
        width: 120,
      },
      {
        id: "grade",
        numeric: false,
        disablePadding: true,
        label: "Grade",
        sort: true,
        width: 120,
      }
    ]
  }
]